# Deployment configuration
max_concurrent_tasks: 5
retry_count: 3
retry_delay: 5
ssh_timeout: 30
command_timeout: 300

default_user: deploy
default_port: 22

template_dir: templates
inventory_file: inventory.yml

ssh_options:
  forward_agent: true
  verify_host_key: true
  keepalive: true
  keepalive_interval: 30

logging:
  level: info
  file: kdeploy.log
